### ISSUE TITLE
Bazel Build using MacOs does not work

### ISSUE THREAD

**Issue by aquintanas** [limdor/p2p-lending#9]
I obtain the following error:

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository pip instantiated at:
  /Users/aquintanas/BSC/git/p2p-lending/WORKSPACE:11:12: in <toplevel>
  /private/var/tmp/_bazel_root/258ef8fd9a91de21d575463e402686bb/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /private/var/tmp/_bazel_root/258ef8fd9a91de21d575463e402686bb/external/rules_python/python/pip_install/pip_repository.bzl:67:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_root/258ef8fd9a91de21d575463e402686bb/external/rules_python/python/pip_install/pip_repository.bzl", line 63, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (Timed out)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_root/258ef8fd9a91de21d575463e402686bb/external/rules_python/python/pip_install/pip_repository.bzl", line 63, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (Timed out)
ERROR: Skipping '//:main': no such package '@pip//': rules_python_external failed:  (Timed out)
WARNING: Target pattern parsing failed.
ERROR: no such package '@pip//': rules_python_external failed:  (Timed out)
INFO: Elapsed time: 616.653s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
```

Build label: 4.2.1-homebrew
MacOS: Big Sur 11.4

**Comment by limdor** [comment]
We should try if with the latest version still happens https://github.com/limdor/p2p-lending/pull/10
